# Generated by Django 4.1.7 on 2023-12-23 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="group",
            new_name="groups",
        ),
    ]
