# Generated by Django 4.1.7 on 2023-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_add_first_level_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название"),
        ),
    ]
