# Generated by Django 4.1.7 on 2023-12-23 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_rename_group_group_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="groups",
            new_name="group",
        ),
    ]
