# Generated by Django 4.1.7 on 2023-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_alter_lesson_week_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="week_day",
            field=models.CharField(
                choices=[
                    ("Понедельник", "Понедельник"),
                    ("Вторник", "Вторник"),
                    ("Среда", "Среда"),
                    ("Четверг", "Четверг"),
                    ("Пятница", "Пятница"),
                    ("Суббота", "Суббота"),
                ],
                default="Понедельник",
                max_length=11,
                verbose_name="День недели",
            ),
        ),
    ]
