# Generated by Django 4.1.7 on 2023-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_alter_lesson_week_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="teacher",
        ),
        migrations.AddField(
            model_name="exam",
            name="teacher",
            field=models.ManyToManyField(
                to="schedule.teacher", verbose_name="Преподаватель"
            ),
        ),
    ]
